# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bash_friend',
                'doc_host': 'https://daburer.github.io',
                'git_url': 'https://github.com/daburer/bash_friend',
                'lib_path': 'bash_friend'},
  'syms': { 'bash_friend.core': { 'bash_friend.core.fmt_query': ('core.html#fmt_query', 'bash_friend/core.py'),
                                  'bash_friend.core.main': ('core.html#main', 'bash_friend/core.py'),
                                  'bash_friend.core.tmux_history': ('core.html#tmux_history', 'bash_friend/core.py')}}}
