"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['tmux_history', 'fmt_query', 'main']

# %% ../nbs/00_core.ipynb 2
from fastcore.script import *
from fastcore.tools import *
from fastcore.utils import *
from lisette import *

# %% ../nbs/00_core.ipynb 9
def tmux_history():
    o = shell('tmux capture-pane -p', capture_output=True, text=True)
    return o.stdout or o.stderr

# %% ../nbs/00_core.ipynb 10
def fmt_query(query):
    query = f'''
<tmux_history>
{tmux_history()}
</tmux_history>
<user_query>
{query}
</user_query>'''
    return query

# %% ../nbs/00_core.ipynb 11
@call_parse
def main(query:str): # Question to ask the bash_friend
    'Bash Friend Assistent for your tmux terminal'
    c = Chat('claude-sonnet-4-5-20250929', tools=[view, rg])
    res = c((fmt_query(query)), max_steps=5)
    print(res.choices[0].message.content)

